Lab 2
DenisBoss2003/Labs pull request #2
Opened 2024-10-19 07:31 UTC by DenisBoss2003

2024-10-19 08:24 UTC, lamer0k requested changes

2024-10-19 08:24 UTC, lamer0k commented on Lab_2.adoc
> +----
[source, cpp]

2024-10-19 08:24 UTC, lamer0k commented on Lab_2.adoc
> +#include <iostream>
Лучше привести пример, со случаем когда теряется точность.

2024-10-19 08:24 UTC, lamer0k commented on Lab_2.adoc
> +    double x = 5.7;
тут 5.7 литерал double, поэтому можно упростить auto x = 5.7;

2024-10-19 08:24 UTC, lamer0k commented on Lab_2.adoc
> +    int y = (int)x; // Явное преобразование double в int
так делать не надо. Это Сишное явное преобразование типа, оно работает так,  первым делом пытается сделать static_cast, если не получается делает const_cast, если не получается делает reinterpret_cast, в итоге  например, такое вот может запросто сработать

const double x = 5.7;
int* y = (int*)x;
*y = 6.2; //Вот тут программа свалится.

А вообще это жестокая ошибка - константа может находиться в ПЗУ, когда ты сделал такое Сишное преобразование, указатель y будет указывать на переменную в ПЗУ, и далее попытается туда записать 6.2. Но суть в том, что в ПЗУ нельзя писать, и программа валится.

Не надо использовать Сишный каст.

2024-10-19 08:24 UTC, lamer0k commented on Lab_2.adoc
> +Таблица <<Размеры и диапазон значений типов>> показывает соответствие типов данных и их размеров в байтах для стандартных типов. В качестве платформы и компилятора используется IAR Workbench.
Тогда уж надо уточнять, что компилятор для ARM 32 битный.

2024-10-19 08:24 UTC, lamer0k commented on Lab_2.adoc
> +[#Размеры и диапазон значений типов ]
Хорошо бы привести формулу допустимых раметров типов для стандарта С++

2024-10-19 08:24 UTC, lamer0k commented on Lab_2.adoc
> +    *modifyValue = 42; // Изменение значения через const_cast
И вот так делать не надо  никогда :).  Поскольку ты не знаешь на что указывает указатель value.

2024-10-19 08:24 UTC, lamer0k commented on Lab_2.adoc
> +    int x = 10;
а теперь сделай глобальную переменную  

constexpr const int x = 10;  и посмотри, что будет

2024-10-19 08:24 UTC, lamer0k commented on Lab_2.adoc
> +    unsigned char mask = ~(1 << bitToReset); // Сдвиг 1 влево и инвертирование
const добавить - маска больше не будет меняться.

2024-10-19 08:24 UTC, lamer0k commented on Lab_2.adoc
> + *Ответ:* 1
Нет

2024-10-19 08:24 UTC, lamer0k commented on Lab_2.adoc
> +*Ответ:* 1
Нет

2024-10-19 08:24 UTC, lamer0k commented on Lab_2.adoc
> +*Ответ:* значение char c
Тип то какой?

2024-11-24 14:42 UTC, lamer0k commented on Lab_2.adoc
> +[#Размеры и диапазон значений типов ]
Где формула то?

2024-11-24 14:45 UTC, lamer0k requested changes
Часть не поправил

2024-11-30 10:54 UTC, lamer0k approved these changes

2024-11-30 10:55 UTC, lamer0k requested changes
ds

2025-01-21 13:17 UTC, DenisBoss2003 commented on Lab_2.adoc
> +----
исправил

2025-01-21 13:17 UTC, DenisBoss2003 commented on Lab_2.adoc
> +#include <iostream>
исправил

2025-01-21 13:18 UTC, DenisBoss2003 commented on Lab_2.adoc
> +    double x = 5.7;
переделал

2025-01-21 13:18 UTC, DenisBoss2003 commented on Lab_2.adoc
> +    int y = (int)x; // Явное преобразование double в int
исправил

2025-01-21 13:18 UTC, DenisBoss2003 commented on Lab_2.adoc
> +Таблица <<Размеры и диапазон значений типов>> показывает соответствие типов данных и их размеров в байтах для стандартных типов. В качестве платформы и компилятора используется IAR Workbench.
исправил

2025-01-21 13:18 UTC, DenisBoss2003 commented on Lab_2.adoc
> +[#Размеры и диапазон значений типов ]
исправил

2025-01-21 13:19 UTC, DenisBoss2003 commented on Lab_2.adoc
> +    unsigned char mask = ~(1 << bitToReset); // Сдвиг 1 влево и инвертирование
снизу привел пример с const

2025-01-21 13:19 UTC, DenisBoss2003 commented on Lab_2.adoc
> + *Ответ:* 1
исправил

2025-01-21 13:19 UTC, DenisBoss2003 commented on Lab_2.adoc
> +*Ответ:* значение char c
исправил

2025-01-25 07:33 UTC, lamer0k approved these changes

2025-01-25 08:53 UTC, merged