Lab3-4
DenisBoss2003/Labs pull request #3
Opened 2024-11-28 16:17 UTC by DenisBoss2003

2024-11-29 12:19 UTC, lamer0k requested changes

2024-11-29 12:19 UTC, lamer0k commented on Lab_2.adoc
> +
Зачем в этом запросе лаба 2?

2024-11-29 12:19 UTC, lamer0k commented on Lab 3-4.adoc
> +
Нет таких регистров. ЭТо кто ChatGPT написал? Она если че собирает со всех архитектур и все в кучу выдает. Тут все смешалось, люди, кони. 

Опиши только, что есть у нашего контроллера.

2024-11-29 12:19 UTC, lamer0k commented on Lab 3-4.adoc
> +. Передача по ссылке: Передача аргументов в функции, что позволяет изменять оригинальные данные.
Это нечто другое, есть передача по ссылке, но в С++ есть отдельная сущность ссылка, и передача по ссылке там отдельный термин не связанный с указателем,  Опять ЧатГПТ?

2024-11-29 12:19 UTC, lamer0k commented on Lab 3-4.adoc
> +- Здесь ref действует как алиас для a. Изменения через ref затрагивают переменную a.
По-русски можно.

2024-11-29 12:19 UTC, lamer0k commented on Lab 3-4.adoc
> +[.source, cpp]
Перед эти надо пустую строку вставить.

2024-11-29 12:19 UTC, lamer0k commented on Lab 3-4.adoc
> +it -> Off();
Это не елочка, это ерунда.

2024-11-29 12:19 UTC, lamer0k commented on Lab 3-4.adoc
> +        it->Light();
ерунда какая-то. ЧТо этот код делает?

2024-11-29 12:19 UTC, lamer0k commented on Lab 3-4.adoc
> +tLeds leds;
Сам писал вверху (или чатГПТ) про ссылки, что они позволяют избежать копирования, и сам же объявил массив, теперь в конструкторе будет копирование массив по ссылке ledsArr в массив leds

2024-11-29 12:19 UTC, lamer0k commented on Lab 3-4.adoc
> +tLeds leds;
Такая же фигня - опять копирование будет

2024-11-29 12:19 UTC, lamer0k commented on Lab 3-4.adoc
> +tLeds leds;
и тут тоже

2024-11-29 12:19 UTC, lamer0k commented on Lab 3-4.adoc
> +[source, cpp]
пустую строку вставить.

2024-11-29 12:19 UTC, lamer0k commented on Lab 3-4.adoc
> +[source, cpp]
тоже пустую строку

2024-11-29 12:19 UTC, lamer0k commented on Lab 3-4.adoc
> +[source, cpp]
и тут

2024-11-29 12:19 UTC, lamer0k commented on Lab 3-4.adoc
> +[source, cpp]
и тут

2024-11-29 12:19 UTC, lamer0k commented on Lab 3-4.adoc
> +[source, cpp]
короче везде перед [source, cpp] ставить пустую строку.

2024-11-29 12:19 UTC, lamer0k commented on Lab 3-4.adoc
> +Таким образом мы получили код, который управляет светодиодами, создавая различные визуальные эффекты, такие как мигание всех светодиодов одновременно, последовательно или в шахматном порядке. В нем и
Раздел выводы добавить

2024-11-29 12:19 UTC, lamer0k commented on Lab 3-4.adoc
> +Таким образом мы получили код, который управляет светодиодами, создавая различные визуальные эффекты, такие как мигание всех светодиодов одновременно, последовательно или в шахматном порядке. В нем и
Добавить описание принципа Одной отвественности, только без ГПТ чатов.

2025-01-21 14:13 UTC, DenisBoss2003 commented on Lab_2.adoc
> +
исправил

2025-01-21 14:14 UTC, DenisBoss2003 commented on Lab 3-4.adoc
> +
убрал лишнее

2025-01-21 14:14 UTC, DenisBoss2003 commented on Lab 3-4.adoc
> +- Здесь ref действует как алиас для a. Изменения через ref затрагивают переменную a.
исправил

2025-01-21 14:14 UTC, DenisBoss2003 commented on Lab 3-4.adoc
> +[.source, cpp]
исправил

2025-01-21 14:14 UTC, DenisBoss2003 commented on Lab 3-4.adoc
> +it -> Off();
переделал

2025-01-21 14:14 UTC, DenisBoss2003 commented on Lab 3-4.adoc
> +        it->Light();
переделал

2025-01-21 14:15 UTC, DenisBoss2003 commented on Lab 3-4.adoc
> +tLeds leds;
не знаю как исправить

2025-01-21 14:15 UTC, DenisBoss2003 commented on Lab 3-4.adoc
> +[source, cpp]
исправил

2025-01-21 14:16 UTC, DenisBoss2003 commented on Lab 3-4.adoc
> +[source, cpp]
исправил

2025-01-21 14:16 UTC, DenisBoss2003 commented on Lab 3-4.adoc
> +[source, cpp]
исправил

2025-01-21 14:16 UTC, DenisBoss2003 commented on Lab 3-4.adoc
> +[source, cpp]
исправил

2025-01-21 14:16 UTC, DenisBoss2003 commented on Lab 3-4.adoc
> +[source, cpp]
исправил

2025-01-21 14:16 UTC, DenisBoss2003 commented on Lab 3-4.adoc
> +Таким образом мы получили код, который управляет светодиодами, создавая различные визуальные эффекты, такие как мигание всех светодиодов одновременно, последовательно или в шахматном порядке. В нем и
добавил

2025-01-21 14:17 UTC, DenisBoss2003 commented on Lab 3-4.adoc
> +Таким образом мы получили код, который управляет светодиодами, создавая различные визуальные эффекты, такие как мигание всех светодиодов одновременно, последовательно или в шахматном порядке. В нем и
добавил

2025-01-25 07:42 UTC, lamer0k requested changes
Еще пару замечаний осталось

2025-01-25 07:42 UTC, lamer0k commented on Lab 3-4.adoc
> +Типы регистров в микроконтроллерах:
Написать про то, что ты занаешь, а не что знает чат джипити - на весь раздел.

2025-01-25 07:42 UTC, lamer0k commented on Lab 3-4.adoc
> +. Указатели на функции: Возможность использовать указатели для вызова функций и передачи их как аргументов.
Теперь надо пояснение, как использовать указатель на функцию, для чего он используется? И что это такое.

2025-01-25 07:42 UTC, lamer0k commented on Lab 3-4.adoc
> +.Экономия ресурсов
Пример привести - когда использование указателей экономит память.

2025-01-25 07:42 UTC, lamer0k commented on Lab 3-4.adoc
> +.Гибкость
Пример привести - когда такое мы уже использовали.

2025-01-25 07:42 UTC, lamer0k commented on Lab 3-4.adoc
> +tLeds leds;
У тебя предыдущая лаба про ссылки была. Надо держать не весь массив а ссылку на него tLeds& leds

2025-01-25 08:47 UTC, DenisBoss2003 commented on Lab 3-4.adoc
> +tLeds leds;
исправил

2025-01-25 08:47 UTC, DenisBoss2003 commented on Lab 3-4.adoc
> +tLeds leds;
исправил

2025-01-25 08:47 UTC, DenisBoss2003 commented on Lab 3-4.adoc
> +tLeds leds;
исправил

2025-01-25 08:47 UTC, DenisBoss2003 commented on Lab 3-4.adoc
> +Типы регистров в микроконтроллерах:
написал про то что знаю

2025-01-25 08:48 UTC, DenisBoss2003 commented on Lab 3-4.adoc
> +. Указатели на функции: Возможность использовать указатели для вызова функций и передачи их как аргументов.
постарался объяснить

2025-01-25 08:48 UTC, DenisBoss2003 commented on Lab 3-4.adoc
> +.Экономия ресурсов
привел пример

2025-01-25 08:48 UTC, DenisBoss2003 commented on Lab 3-4.adoc
> +.Гибкость
привел пример из нашей программы

2025-01-25 10:42 UTC, lamer0k approved these changes

2025-01-25 10:42 UTC, merged