Lab 5 6
DenisBoss2003/Labs pull request #4
Opened 2024-12-27 14:30 UTC by DenisBoss2003

2024-12-28 14:07 UTC, lamer0k requested changes
Надо поправить

2024-12-28 14:07 UTC, lamer0k commented on lab 5-6.adoc
> +
Титульник

2024-12-28 14:07 UTC, lamer0k commented on lab 5-6.adoc
> +        delay(10000);
Код не будет работать.

2024-12-28 14:07 UTC, lamer0k commented on lab 5-6.adoc
> +- Директивы препроцессора для завершения: Завершение секции защиты от множественного включения.
что это? Завершения чего?

2024-12-28 14:07 UTC, lamer0k commented on lab 5-6.adoc
> +    virtual bool Click() = 0;
IsClick()

2024-12-28 14:07 UTC, lamer0k commented on lab 5-6.adoc
> +    if (modes[currentModeType]) {
ернуда

2024-12-28 14:07 UTC, lamer0k commented on lab 5-6.adoc
> +    if (modes[currentModeType]) {
ернуда

2024-12-28 14:07 UTC, lamer0k commented on lab 5-6.adoc
> +    if (modes[currentModeType]) {
ернуда

2024-12-28 14:07 UTC, lamer0k commented on lab 5-6.adoc
> +    currentModeType = (currentModeType + 1) % 3;
Почему 3, а не 42?

2025-01-22 10:18 UTC, DenisBoss2003 commented on lab 5-6.adoc
> +
добавил

2025-01-22 10:18 UTC, DenisBoss2003 commented on lab 5-6.adoc
> +        delay(10000);
исправил

2025-01-22 10:18 UTC, DenisBoss2003 commented on lab 5-6.adoc
> +- Директивы препроцессора для завершения: Завершение секции защиты от множественного включения.
убрал

2025-01-22 10:19 UTC, DenisBoss2003 commented on lab 5-6.adoc
> +    virtual bool Click() = 0;
исправил

2025-01-22 10:19 UTC, DenisBoss2003 commented on lab 5-6.adoc
> +    if (modes[currentModeType]) {
переделал

2025-01-22 10:19 UTC, DenisBoss2003 commented on lab 5-6.adoc
> +    if (modes[currentModeType]) {
переделал

2025-01-22 10:19 UTC, DenisBoss2003 commented on lab 5-6.adoc
> +    if (modes[currentModeType]) {
переделал

2025-01-22 10:19 UTC, DenisBoss2003 commented on lab 5-6.adoc
> +    currentModeType = (currentModeType + 1) % 3;
переделал

2025-01-25 07:43 UTC, lamer0k commented on lab 5-6.adoc
> +
Нету его, в отчете должен быть

2025-01-25 07:44 UTC, lamer0k commented on lab 5-6.adoc
> +    virtual bool Click() = 0;
нет не исправил.

2025-01-25 07:47 UTC, lamer0k requested changes
Отсалось пару замечаний

2025-01-25 07:47 UTC, lamer0k commented on lab 5-6.adoc
> +        if (button.Click())
минор два раза зачем?

2025-01-25 07:47 UTC, lamer0k approved these changes

2025-01-25 10:42 UTC, merged