lab7
DenisBoss2003/Labs pull request #5
Opened 2024-12-28 10:56 UTC by DenisBoss2003

2024-12-28 14:24 UTC, lamer0k requested changes
Надо поправить

2024-12-28 14:24 UTC, lamer0k commented on lab_7.adoc
> +:author: Газенкампф Денис Валерьевич КЭ-413
верни обратно лабу 1 и картинки к ней.

2024-12-28 14:24 UTC, lamer0k commented on lab_7.adoc
> +
Титульник

2024-12-28 14:24 UTC, lamer0k commented on lab_7.adoc
> +- В регистр VAL записывается значение 0, чтобы обнулить счётчик.
== LOAD, а не  0.

2024-12-28 14:24 UTC, lamer0k commented on lab_7.adoc
> +
Диаграмму UML надо хотя бы одну.

2024-12-28 14:24 UTC, lamer0k commented on lab_7.adoc
> +- с инкрементальными энкодерами и датчиками Холла,
что такое инкрементальный энкодер?

2024-12-28 14:24 UTC, lamer0k commented on lab_7.adoc
> +  TIM2::ARR::Write(timeInMs);
Время задано в миллисекундах, а таймер пишется в циклах таймера - где перевод из миллисекунд в цкиклы таймера?

2024-12-28 14:24 UTC, lamer0k commented on lab_7.adoc
> +    delay(2000);
слишком большая задержка

2025-01-25 07:48 UTC, DenisBoss2003 commented on lab_7.adoc
> +:author: Газенкампф Денис Валерьевич КЭ-413
исправил

2025-01-25 07:48 UTC, DenisBoss2003 commented on lab_7.adoc
> +
исправил

2025-01-25 07:48 UTC, DenisBoss2003 commented on lab_7.adoc
> +- В регистр VAL записывается значение 0, чтобы обнулить счётчик.
исправил

2025-01-25 07:48 UTC, DenisBoss2003 commented on lab_7.adoc
> +
добавил

2025-01-25 07:49 UTC, DenisBoss2003 commented on lab_7.adoc
> +- с инкрементальными энкодерами и датчиками Холла,
написал

2025-01-25 07:49 UTC, DenisBoss2003 commented on lab_7.adoc
> +  TIM2::ARR::Write(timeInMs);
исправил

2025-01-25 07:49 UTC, DenisBoss2003 commented on lab_7.adoc
> +    delay(2000);
исправил

2025-01-25 08:04 UTC, lamer0k approved these changes

2025-01-25 08:05 UTC, lamer0k approved these changes

2025-01-25 10:49 UTC, merged